name: MLflow CI Training + Docker

on:
  push:
    branches: [ main, master ]
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install "mlflow[extras]" scikit-learn joblib matplotlib seaborn pandas

      - name: Run MLflow Project
        working-directory: ./MLProject
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
          MLFLOW_ALLOW_FILE_STORE: "true"
        run: mlflow run . --env-manager=local

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: MLProject/mlruns/

            # ================= DOCKER BUILD & PUSH =================
      - name: Build & Push Docker Image
        if: success()
        working-directory: ./MLProject
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "🔍 Mencari model path..."
          MODEL_PATH=$(find mlruns -type d -name "model" | head -n 1)
          echo "Model path: $MODEL_PATH"
          
          if [ -z "$MODEL_PATH" ]; then
            echo "❌ Model path tidak ditemukan!"
            exit 1
          fi
          
          echo "🏗️ Building Docker image..."
          mlflow models build-docker -m "$MODEL_PATH" -n $DOCKER_USERNAME/breast-cancer-model
          
          echo "🔑 Login to Docker Hub..."
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          
          echo "📤 Pushing Docker image..."
          docker push $DOCKER_USERNAME/breast-cancer-model:latest
          
          echo "✅ Docker image berhasil di-push!"